index:
    path: /ajouter-car
    controller: App\Controller\MainController::index
consultation:
    path: /consultation
    controller: App\Controller\MainController::consultation
car:
    path: /car/{id}
    controller: App\Controller\MainController::car
    requirements:
        id: '\d+'

ajout_panne:
    path: /panne/{id}
    controller: App\Controller\MainController::addPanne
    requirements:
        id: '\d+'

recherche:
    path: /recherche
    controller: App\Controller\MainController::recherche

liste_panne:
    path: /liste-panne
    controller: App\Controller\MainController::listePanne

edit_car:
    path: /editcar/{id}
    controller: App\Controller\MainController::editCar
    requirements:
        id: '\d+'
effacer_car:
    path: /effacer-car/{id}
    controller: App\Controller\MainController::deleteCar
    requirements:
        id: '\d+'

edit_panne:
    path: /edit-panne/{id}
    controller: App\Controller\MainController::editPanne
    requirements:
        id: '\d+'

edit_panne_ant:
    path: /edit-panne-ant/{id}
    controller: App\Controller\MainController::editPanneAnt
    requirements:
        id: '\d+'

delete_panne:
    path: /delete_panne/{id}
    controller: App\Controller\MainController::deletePanne
    requirements:
        id: '\d+'

change_etat_car:
    path: /change_etat/{id}
    controller: App\Controller\MainController::changeEtatCar
    requirements:
        id: '\d+'


